name: Get Data and Deploy
# on: push

jobs:
  getdata:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: python .github/get_data.py
        env:
          DEFAULT_BRANCH: main
          DATA_SOURCE: ${{ secrets.DATA_SOURCE }}